---
title: "concurso_comovamos"
author: "Manuel Enriquez"
date: "2024-07-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Limpieza de Base de Datos
```{r}
library(readxl)
library(dplyr)
```

## Lectura de Archivo
```{r}
bd_comovamos <- read_excel("Desktop/DataScience/bases de datos/bd_comovamos.xlsx", sheet = "eav2023")
```
## Limpieza Final

*Paso 1:* Contamos NAs para priorizar aquellas preguntas que no quieran 

```{r}
# Paso 1
variables <- c("quehaceres_hogar", "cuidado_personas", "total_min_trabajo_rem_y_norem","P10","P26","P34","P38_1", "P38_2", "P38_3", "P38_4", "P38_5", "P38_6", "P38_7", "P38_8", "P39","P40", "P41", "P42", "P46_1", "P46_2", "P46_3", "P46_4","P46_5", "P47", "P48", "P49", "P50", "P51", "P52_1", "P52_2", "P52_3", "P52_4","P52_5", "P53", "P54_1", "P54_2", "P54_3", "P54_4", "P54_5", "P54_6", "P55_1","P55_2", "P55_3", "P55_4", "P58", "P59", "P60","P63", "P64", "P65", "P66", "P67","P68_16","P69", "P70_1", "P70_2", "P70_3", "P70_4","P71", "P72", "P74", "P75","P90", "P91_1", "P91_2","P91_3", "al_menos_un_problema_mental", "P92", "P93", "P94", "P95","P99", "P100_1", "P100_2")
df_cvnl <- bd_comovamos %>% select(all_of(variables))
df_cvnl <- df_cvnl[complete.cases(df_cvnl),]

# Paso 2
df_cvnl <- df_cvnl %>%
  rename(
    P10 = motivo_traslado
    P26 = transporte_publico
    P33 = bicicletas
    P64 = futuro_economico_del_hogar
    P65 = ingreso_del_hogar
    P66 = empresas_extranjeras
    P67 = oportunidades_mujeres
    P69 = percepcion_de_num_migrantes
    P70_1 = migrantes_admitidos
    P70_2 = migrantes_y_permisos
    P70_3 = migrantes_y_empleo
    P70_4 = migrantes_e_inseguridad
    P71 = diabetes
    P72 = hipertension
    P74 = sobrepeso_obesidad
    P75 = problema_de_salud
    P90 = salud_municipal
    P91_1 = decaido_y_deprimidio
    P91_2 = nervios_y_ansiedad
    P91_3 = calidad_de_sueño
    P92 = problema_de_desarrollo
    P93 = seguridad_municipal
    P94 = lugar_inseguro
    P95 = victima_de_delito
    P99 = investigacion_delitos
    P_100_1 = presencia_policial
    P100_2 = seguridad_policial
  )
```

```{r}
dat %>% select(col())
```

